---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: Install Packages
  apt:
    pkg:
    - apt-transport-https
    - ntp
    - python3
    - tcpdump
    - wget
    - openssl
    - curl
    state: latest
    update_cache: yes
    autoremove: yes
